In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('play_tennis.csv')

In [3]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
df.shape

(14, 6)

In [6]:
#problem 1
#outlook=Sunny,Temp=Hot,Wind=weak,Humidity=high
#play or not play

In [7]:
#solution using naive bayes
#P(Yes | sunny,hot,high,weak)=P(Yes|sunny) *P(Yes|hot) *P(Yes|high)* P(Yes|weak)*p(yes)
#P(No | sunny,hot,high,weak)=P(NO|sunny)* P(No|hot)* P(No|high)* P(No|weak)*p(no)

#compare both and which ever is maximum that is answer(Maximum a posteriori rule)

In [8]:
#problem 2
#outlook=Overcast,Temp=Hot,Wind=weak,Humidity=high
#play or not play

In [9]:
#solution using naive bayes
#P(Yes | Outlook,hot,high,weak)=P(Yes|Outlook) *P(Yes|hot) *P(Yes|high)* P(Yes|weak)*p(yes)
#P(No | Outlook,hot,high,weak)=P(NO|Outlooky)* P(No|hot)* P(No|high)* P(No|weak)*p(no)

#compare both and which ever is maximum that is answer(Maximum a posteriori rule)

In [11]:
#Training
#Lookup Table(Dictionary)(storing probability)
#Testing

In [12]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [13]:
py=9/14
pn=5/14

In [14]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [17]:
#outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [18]:
Pon=0
Prn=2/5
Psn=3/5
Poy=4
Pry=3/5
Psy=2/5

In [19]:
#temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [25]:
Pcn=1/5
Phn=2/5
Pmn=2/5

Pcy=3/9
Phy=2/9
Pmy=4/9

In [21]:
#humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [26]:
Phighn=4/5
Pnormaln=1/5

Phighy=3/9
Pnormaly=6/9

In [23]:
#wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [28]:
Pstrongn=3/5
Pweakn=2/5

Pstrongy=3/9
Pweaky=6/9

In [31]:
#outlook=Sunny,Temp=Hot,Wind=weak,Humidity=high

Pyes=py*Psy*Phy*Phighy*Pweaky
print(Pyes)

0.012698412698412698

In [32]:
Pno=pn*Psn*Phn*Phighn*Pweakn
print(Pno)

0.02742857142857143

In [33]:
#pno>pyes  then no play